using UnityEngine;
using System.Collections;

public class CAudioManager : MonoBehaviour
{
	private static CAudioManager _instance;
	public static CAudioManager instance
	{
		get
		{
			if (_instance == null)
			{
				_instance = FindObjectOfType<CAudioManager>();
			}
			if (_instance == null)
			{
				GameObject go = new GameObject("AudioManager_autogenerated");
				_instance = go.AddComponent<CAudioManager>();
			}
            return _instance;
        }
    }

	public AudioSource _sfxSource;
	public AudioSource _MusicSource;

    public AudioClip acDowngrade, acUpgrade;
	
	public AudioSource SfxSource
	{
		get
		{
			if (_sfxSource == null)
			{
				_sfxSource = GetComponent<AudioSource>();
			}
			return _sfxSource;
		}
	}
	
	public AudioSource MusicSource
	{
		get
		{
			if(_MusicSource == null)
			{
				foreach(Transform tr in this.transform)
					if(tr.name == "Music")
						_MusicSource = tr.GetComponent<AudioSource>();
			}
			return _MusicSource;
		}
	}
			
	public void PlaySound(AudioClip clip)
	{
		SfxSource.clip = clip;
		SfxSource.PlayControlled(AudioType.Sound);
	}
	
	public void PlayMusic(AudioClip clip)
	{
		MusicSource.clip = clip;
		MusicSource.PlayControlled(AudioType.VoiceOver);
	}

	//public void SwitchMusic(AudioClip music)
	//{
	//	StartCoroutine(SwitchMusicCoroutine(music));
	//}

	//public void SwitchToMainMusic()
	//{
	//	StartCoroutine(SwitchMusicCoroutine(mainMusic));
	//}

	//IEnumerator SwitchMusicCoroutine(AudioClip music)
	//{
	//	musicSource.GetOrAddComponent<VolumeTweenable>().Tween(0.1f, 0.5f);
	//	yield return new WaitForSeconds(0.5f);
	//	musicSource.clip = music;
	//	musicSource.Play();
	//	musicSource.GetOrAddComponent<VolumeTweenable>().Tween(1f, 0.5f);
	//}
	
	public void Pause()
	{
		MusicSource.Pause();
		SfxSource.Pause();
	}
	
	public void Resume()
	{
		MusicSource.UnPause();
		SfxSource.UnPause();
	}
	
	public bool IsAudioPlaying()
	{
		bool bSFX = SfxSource.isPlaying;
		
		if(bSFX)
			return true;
		
		return false;
	}
	
	public void StopAll()
	{
		MusicSource.Stop();
		SfxSource.Stop();
	}
}
